// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kimorwlrvulgdknvclqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbW9yd2xydnVsZ2RrbnZjbHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODcxMTYsImV4cCI6MjA2NTk2MzExNn0.KC7cqdEHFRD5ef37DazmeAp_v1dMEjlH32qc2odoFck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);